name: Programar acción para actualizar el archivo README
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Obtener contenido actual del archivo README
        run: |
          content=$(cat README.md)

          # Modificar la línea deseada
          modified_content=$(echo "$content" | sed -E 's/Jhorman \(<img id="son" src="https:\/\/img\.shields\.io\/badge\/([0-9]+)-white\?style=for-the-badge"\/>\) and Ana \(<img id="dau" src="https:\/\/img\.shields\.io\/badge\/([0-9]+)-white\?style=for-the-badge"\/>\)/Jhorman (<img id="son" src="https:\/\/img.shields\.io\/badge\/$(( $(date +%Y) - 2004 ))-white\?style=for-the-badge"\/>) and Ana (<img id="dau" src="https:\/\/img\.shields\.io\/badge\/$(( $(date +%Y) - 2018 ))-white\?style=for-the-badge"\/>)/g')

          # Escribir el contenido actualizado de vuelta al archivo README
          echo "$modified_content" > README.md

      - name: Commit y push de los cambios al repositorio
        uses: EndBug/add-and-commit@v7
        with:
          message: "Actualizar archivo README automáticamente"
          add: README.md
          author_email: omartinez@gmail.com
          author_name: Octavio Martínez
