name: Programar acción para actualizar el archivo README
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Obtener contenido actual del archivo README
        run: |
          content=$(cat README.md);
          modified_content=$(echo "$content" | sed -E 's/Jhorman \(([0-9]+)\) and Ana \(([0-9]+)\)/Jhorman ($(( $(date +%Y) - 2004 ))) and Ana ($(( $(date +%Y) - 2018 )))/g');
          echo "$modified_content" > README.md;

      - name: Commit y push de los cambios al repositorio
        uses: EndBug/add-and-commit@v7
        with:
          message: "Actualizar archivo README automáticamente"
          add: README.md
          author_email: omartinez@gmail.com
          author_name: Octavio Martínez
